### ISSUE TITLE
Subsystem for markings failing to start.

### ISSUE THREAD

**Issue by Andron1219** [Equinox-SS13/equinox-sojourn#11]
Some rounds it appears the marking subsystem will shut itself off. There isn't any ability to find data to replicate this, as this seems to just be a crash of one of the subsystems. Perhaps overuse of char creation caused it to crash?

**Comment by Michiyamenotehifunana** [comment]
As the marking system has been refactored and this issue has not manifested itself since then, I am considering this fixed until we see it happen again.
