### ISSUE TITLE
Certain food recipes cannot accept produce.

### ISSUE THREAD

**Issue by Awesome4Real** [Equinox-SS13/equinox-sojourn#34]
Some food recipes that use the "Cooking With Jane" code cannot accept some 'produce' ingredients.

I found this when I was trying to cook a vegetable pizza, that it was not accepting the mushrooms. Every other step where I needed to add produce worked just fine. I am not sure where the issue is.

The ingredient steps that I've found don't work for any recipe are:
- mushrooms (meant to accept chanterelle)
- poppies (meant to accept poppy flowers)

there may be more that I am unaware of.

**Comment by SigDoesCode** [comment]
So I solved part of this issue.
The gist of it is that the add_produce check was comparing the added item's associated seed datum's *seed name* variable to the recipe's requested seed datum's *name* variable. Most of the seed datums have these two the same, but it's different on some of them, including, funnily enough, chanterelle mushrooms and poppies. Why? I have no idea, but that's how it was coded.

I've fixed that in some code that I've written but I've run into a couple of other issues, namely that one can add *infinite* produce to something if it's asking for produce, and that the oven just doesn't work to cook food. I'l look at his asap

**Comment by Takykardi** [comment]
> Currently fixed via PR #54 , can be closed once that's in?

For future reference, you can link issues in pull requests. IE in #54 you just have to add something like "fixes #34" or "closes #34" in the description, and it'll automatically close the issue once it's merged due to the linked PR. Since #54 has been merged, I'll be closing this issue out.
